version: '3'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: